// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function GetTimeOption() {
  return window['go']['main']['App']['GetTimeOption']();
}

export function GetUUID(arg1) {
  return window['go']['main']['App']['GetUUID'](arg1);
}

export function Md5Encode(arg1) {
  return window['go']['main']['App']['Md5Encode'](arg1);
}

export function SetDatetime(arg1) {
  return window['go']['main']['App']['SetDatetime'](arg1);
}

export function SetFormat(arg1) {
  return window['go']['main']['App']['SetFormat'](arg1);
}

export function SetLocation(arg1) {
  return window['go']['main']['App']['SetLocation'](arg1);
}

export function SetUnix(arg1) {
  return window['go']['main']['App']['SetUnix'](arg1);
}

export function StrLength(arg1) {
  return window['go']['main']['App']['StrLength'](arg1);
}

export function TimeInit() {
  return window['go']['main']['App']['TimeInit']();
}

export function UrlDecode(arg1) {
  return window['go']['main']['App']['UrlDecode'](arg1);
}

export function UrlEncode(arg1) {
  return window['go']['main']['App']['UrlEncode'](arg1);
}
