// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {timex} from '../models';

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function GenerateQRCode(arg1:string):Promise<string>;

export function GetTimeOption():Promise<timex.TimeOption>;

export function Md5Encode(arg1:string):Promise<string>;

export function SetDatetime(arg1:string):Promise<void>;

export function SetFormat(arg1:string):Promise<void>;

export function SetLocation(arg1:string):Promise<void>;

export function SetUnix(arg1:number):Promise<void>;

export function StrLength(arg1:string):Promise<number>;

export function TimeInit():Promise<timex.TimeOption>;

export function UrlDecode(arg1:string):Promise<string>;

export function UrlEncode(arg1:string):Promise<string>;
