// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}
